env: devs
#  context-path: /dev
spring:
  datasource: # 数据库连接池配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/paascloud_uac?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: new_pass
    type: com.alibaba.druid.pool.DruidDataSource
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#    filters: stat

  jpa: # jpa配置
    hibernate:
#      ddl-auto: create # 会在首次启动的时候根据相应的实体类在数据库中创建相应的表，如果之前有表了，就会删掉在重建
#      ddl-auto: update # 如果没有表会创建，有表会对表结构进行修改
#     ddl-auto:create-drop # 应用停下来时会将表删掉
      ddl-auto: none  # 什么都不做（默认值）
#      ddl-auto: validate # 检查实体类字段和表字段是否一致，如果不一致就会报错
    show-sql: true # 执行数据库操作时会打印出相应的SQL语句

#  mvc:
#    view: # jsp文件路径设置
#      prefix: /WEB-INF/jsp/ # jsp视图前缀
#      suffix: .jsp # jsp视图后缀

#  redis: # rediss缓存设置
#    host: 127.0.0.1 # 监听IP地址
#    port: 6379 # 端口号
#    pool:
#      max-idle: 20
#      min-idle: 1
#      max-active: 20
#      max-wait: 60000
#    database: 0
