nan: device
spring:
  datasource:
    url: jdbc:mysql://mydbaicamera.coibvptmcw0p.us-west-2.rds.amazonaws.com:3306/aicamera?characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8
    username: camera_user
    password: Xx20190610*
    #下面为连接池的补充设置，应用到上面所有数据源丿
    # 初始化大小，最小，最夿
    initialSize: 10
    minIdle: 10
    maxActive: 100
    # 配置获取连接等待超时的时闿
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大尿
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

# mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.whxx.dooebell.doorbellproviderdevice.model

#  bossGroup\u7684\u7EBF\u7A0B\u6570
boss:
  thread:
    count: 2
# worker\u7684\u7EBF\u7A0B\u6570
worker:
  thread:
    count: 2
#\u662F\u5426\u4F7F\u7528\u957F\u8FDE\u63A5
so:
  keepalive: true
  backlog: 100
#quickserver
quickserver:
  port: 8087

#jiguang send
if:
  send:
    product: true
eureka:
  client:
    # 客户端在注册时就会使用自己的ip地址而不是主机名(客户端自身加)#
    #registerWithEureka: false
    #是否需要去检索寻找服务，默认是true
    #fetchRegistry: false
    #eureka服务器的地址（注意：地址最后面的 /eureka/ 这个是固定值）
    service-url:
      defaultZone: http://localhost:1000/eureka




