name: doorbell-gateway-dev.yml
zuul:
  routes:
    uac:
      path: /myUac/**
      serviceId: doorbell-provider-uac
      sensitiveHeaders:
      
# ========添加配置======= 查看全部路由要加这些 http://127.0.0.1:1001/actuator/routes
management:
  endpoints:
    web:
      exposure:
        include: "*" #注意这里*要加引号，暴露全部，也可以只暴露相应endpoint
  endpoint:
    routes:
      enabled: true # 默认为true，可以省略
      
spring:
  redis:
    host: 127.0.0.1
    port: 6379
